### ISSUE TITLE
Data Write back

### ISSUE THREAD

**Issue by dharmeshbhana** [jamesridgway/sunsynk-api-client#3]
Hi

This looks like a new & recent ? Anybody had issues so far?

Can one change Inverter settings with this?

Thanks

**Comment by jamesridgway** [comment]
Hi @dharmeshbhana 

Currently this only allows for retreiving data from the inverter, but I believe it should be possible to write data back. Do you know what inverter settings you are looking to change?

**Comment by dharmeshbhana** [comment]
Hi

Mainly SOC %, and switching on and off grid charge. Idea is based on cloud cover, load shedding times to change these settings.

Thanks

**Comment by dharmeshbhana** [comment]
Oh and can this be installed via HACS into HASS? Procedure to install?

**Comment by jamesridgway** [comment]
I have built a home assistant integration which uses this that is up for review at the moment so I'm hoping this will get accepted into the Home Assistant codebase soon.

**Comment by dharmeshbhana** [comment]
Great, will await!

**Comment by jamesridgway** [comment]
If you feel like helping out, this is the pull request:
https://github.com/home-assistant/core/pull/85893

And these are the HA guidelines for pull requests, so if you're able to helpout with a review or pulling the changes and testing them that's be really helpful. The guidelines for HA pull request reviews are here:
https://developers.home-assistant.io/docs/review-process/

**Comment by dharmeshbhana** [comment]
Would like to help out, but need some guidance on pulling the changes and testing...
